channels:
- conda-forge
dependencies:
- python=3.11.14
- pip<=25.3
- pip:
  - mlflow==3.5.1
  - cloudpickle==2.2.1
  - numpy==1.24.3
  - psutil==7.1.1
  - scikit-learn==1.2.2
  - scipy==1.15.3
name: mlflow-env
